backend:
  name: github
  repo: Regihub/fara
  branch: main
  base_url: https://fara-beta-pink.vercel.app/api
  auth_endpoint: auth

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "weeks"
    label: "Farské oznamy"
    folder: "src/content/weeks"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    identifier_field: "title"

    fields:
      - { label: "Názov", name: "title", widget: "string" }
      - { label: "Číslo týždňa", name: "weekNumber", widget: "number", value_type: "int" }
      - { label: "Rok", name: "year", widget: "number", value_type: "int" }

      - label: "Platné od"
        name: "weekStart"
        widget: "datetime"
        format: "YYYY-MM-DD"
        date_format: "YYYY-MM-DD"
        time_format: false

      - label: "Platné do"
        name: "weekEnd"
        widget: "datetime"
        format: "YYYY-MM-DD"
        date_format: "YYYY-MM-DD"
        time_format: false

      - { label: "Všeobecné oznamy", name: "general", widget: "markdown" }

      - label: "Sväté omše"
        name: "masses"
        widget: "list"
        collapsed: false
        summary: "{{fields.day}} {{fields.date}} {{fields.time}}"
        fields:
          - { label: "Deň", name: "day", widget: "string" }
          - { label: "Dátum", name: "date", widget: "string" }
          - { label: "Čas", name: "time", widget: "string" }
          - { label: "Úmysel", name: "intention", widget: "string", required: false }
          - { label: "Slávime", name: "note", widget: "string", required: false }          
          - { label: "Miesto", name: "place", widget: "string", required: false }
